# Generated by Django 5.0.3 on 2024-04-07 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvailableTimes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("availabletimes", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "available_times",
            },
        ),
        migrations.CreateModel(
            name="StaffUser",
            fields=[
                (
                    "staff_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=100)),
                ("firstname", models.CharField(max_length=25)),
                ("lastname", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "staff_user",
            },
        ),
        migrations.CreateModel(
            name="GeneratedTimetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chosentimes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ga_api.availabletimes",
                    ),
                ),
                (
                    "staffuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ga_api.staffuser",
                    ),
                ),
            ],
            options={
                "db_table": "generated_timetable",
            },
        ),
        migrations.CreateModel(
            name="StudentUser",
            fields=[
                (
                    "student_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=100)),
                ("firstname", models.CharField(max_length=25)),
                ("lastname", models.CharField(max_length=30)),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ga_api.staffuser",
                    ),
                ),
            ],
            options={
                "db_table": "student_user",
            },
        ),
    ]
